datastore:
  filename: stats.sqlite
scheduler:
  period_sec: 5
  start_time: 2022-11-16 08:03:25.064681+00:00
storage_food:
  url: http://localhost:8090/food-stats
storage_merch:
  url: http://localhost:8090/merch-stats
version: 1
