version: 1
storage_merch:
  url: http://127.0.0.1:8090/merch-inventory
storage_food:
  url: http://127.0.0.1:8090/food-inventory

services:
  receiverStats: http://steven-kafka-apple-banana.eastus.cloudapp.azure.com/receiver/health
  storageStats:  http://steven-kafka-apple-banana.eastus.cloudapp.azure.com/storage/health
  processingStats:  http://steven-kafka-apple-banana.eastus.cloudapp.azure.com/processing/health
  auditStats:  http://steven-kafka-apple-banana.eastus.cloudapp.azure.com/audit/health


kafka: # topic 
  hostname: steven-kafka-apple-banana.eastus.cloudapp.azure.com
  port: 9092
  topic: events
kafkaFood:
  hostname: steven-kafka-apple-banana.eastus.cloudapp.azure.com
  port: 9092
  topic: kafkaAddFood