version: 1
datastore:
  user: root
  password: Steven646!
  hostname: localhost
  port: 3306
  db: inventory

cloudstore:
  user: user
  password: Steven646!
  hostname: steven-kafka-apple-banana.eastus.cloudapp.azure.com
  port: 3306
  db: inventory